/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package studentgradingmanager.UI.teacher.jpanel;

/**
 *
 * @author Quan
 */
public class TeacherSearch extends javax.swing.JPanel {

    /**
     * Creates new form TeacherSearch
     */
    public TeacherSearch() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpTeacherSearch = new javax.swing.JPanel();
        jtfSearchForStudent = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jbSearch = new javax.swing.JButton();
        jScrollPane = new javax.swing.JScrollPane();
        jtStudents = new javax.swing.JTable();

        jpTeacherSearch.setBackground(new java.awt.Color(255, 255, 255));
        jpTeacherSearch.setForeground(new java.awt.Color(255, 255, 255));
        jpTeacherSearch.setPreferredSize(new java.awt.Dimension(760, 540));

        jtfSearchForStudent.setBackground(new java.awt.Color(217, 217, 217));
        jtfSearchForStudent.setForeground(new java.awt.Color(153, 153, 153));
        jtfSearchForStudent.setText("Nhập tên / mã học sinh cần tìm");
        jtfSearchForStudent.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jtfSearchForStudent.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtfSearchForStudentMouseClicked(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/studentgradingmanager/images/icon-search-16.png"))); // NOI18N

        jbSearch.setBackground(new java.awt.Color(169, 186, 247));
        jbSearch.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jbSearch.setForeground(new java.awt.Color(255, 255, 255));
        jbSearch.setText("Tìm kiếm");
        jbSearch.setBorder(null);
        jbSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSearchActionPerformed(evt);
            }
        });

        jScrollPane.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane.setForeground(new java.awt.Color(255, 255, 255));

        jtStudents.setBackground(new java.awt.Color(255, 255, 255));
        jtStudents.setForeground(new java.awt.Color(0, 0, 0));
        jtStudents.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "STT", "Mã học sinh", "Tên học sinh", "Lớp", "GVCN"
            }
        ));
        jtStudents.setGridColor(new java.awt.Color(0, 0, 0));
        jtStudents.setShowGrid(true);
        jScrollPane.setViewportView(jtStudents);
        if (jtStudents.getColumnModel().getColumnCount() > 0) {
            jtStudents.getColumnModel().getColumn(0).setPreferredWidth(45);
            jtStudents.getColumnModel().getColumn(1).setPreferredWidth(150);
            jtStudents.getColumnModel().getColumn(2).setPreferredWidth(300);
            jtStudents.getColumnModel().getColumn(3).setPreferredWidth(100);
            jtStudents.getColumnModel().getColumn(4).setPreferredWidth(300);
        }

        javax.swing.GroupLayout jpTeacherSearchLayout = new javax.swing.GroupLayout(jpTeacherSearch);
        jpTeacherSearch.setLayout(jpTeacherSearchLayout);
        jpTeacherSearchLayout.setHorizontalGroup(
            jpTeacherSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpTeacherSearchLayout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(jpTeacherSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpTeacherSearchLayout.createSequentialGroup()
                        .addComponent(jtfSearchForStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1)
                        .addGap(83, 83, 83)
                        .addComponent(jbSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 637, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(69, Short.MAX_VALUE))
        );
        jpTeacherSearchLayout.setVerticalGroup(
            jpTeacherSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpTeacherSearchLayout.createSequentialGroup()
                .addGroup(jpTeacherSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpTeacherSearchLayout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addGroup(jpTeacherSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jbSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtfSearchForStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpTeacherSearchLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addGap(10, 10, 10)))
                .addGap(36, 36, 36)
                .addComponent(jScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(166, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpTeacherSearch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpTeacherSearch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jbSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbSearchActionPerformed

    private void jtfSearchForStudentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtfSearchForStudentMouseClicked
        if (jtfSearchForStudent.getText().equals("Nhập tên / mã học sinh cần tìm")) {
            jtfSearchForStudent.setText("");
        }
    }//GEN-LAST:event_jtfSearchForStudentMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane;
    private javax.swing.JButton jbSearch;
    private javax.swing.JPanel jpTeacherSearch;
    private javax.swing.JTable jtStudents;
    private javax.swing.JTextField jtfSearchForStudent;
    // End of variables declaration//GEN-END:variables
}
