/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package studentgradingmanager.UI.teacher.jpanel;

import Database.DBConnect;
import OOP.DIEM;
import OOP.StudentBase;
import TransferData.MessageBroker;
import java.awt.Dimension;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

import java.util.ArrayList;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Quan
 */
public class TeacherGradingManagementNewSubjectFrame extends javax.swing.JFrame {

    private StudentBase studentBase;
    private List<String> listMAHK;
    private List<String> listNAMHOC;

    /**
     * Creates new form TeacherGradingManagementNewSubjectFrame
     */
    public TeacherGradingManagementNewSubjectFrame(StudentBase studentBase) {
        initComponents();

        this.studentBase = studentBase;
        mirrorData();
        findSemester();
    }

    private void mirrorData() {
        jlbAddSubjectFor.setText("Thêm môn học cho học sinh " + studentBase.getHOTEN());
        jlbAddSubjectFor.setPreferredSize(new Dimension(0, 0));

    }

    private void findSemester() {
        listMAHK = new ArrayList<>();
        // tim MAHK
        try {
            java.sql.Connection connection = DBConnect.getConnection();
            //JOptionPane.showMessageDialog(this, "Xin chào giáo viên " + matkGV);

            String sql = "SELECT * FROM HOCKYNAMHOC";
            PreparedStatement statement = connection.prepareStatement(sql);
            ResultSet resultSet = statement.executeQuery();
            if (resultSet.next()) {
                listMAHK.add(resultSet.getString("MAHK"));
            }
            if (!statement.isClosed()) {
                statement.close();
                System.out.println("Close SEARCH MAHK");
            }
        } catch (SQLException ex) {
            Logger.getLogger(TeacherSearchResultFrame.class.getName()).log(Level.SEVERE, null, ex);
        }

        // add data vao jComboBox
        listNAMHOC = new ArrayList<>();
        try {
            java.sql.Connection connection = DBConnect.getConnection();
            //JOptionPane.showMessageDialog(this, "Xin chào giáo viên " + matkGV);

            String sql = "SELECT * FROM HOCKYNAMHOC";
            PreparedStatement statement = connection.prepareStatement(sql);
            ResultSet resultSet = statement.executeQuery();
            boolean isPresent = false;
            while (resultSet.next()) {
                if (listNAMHOC.size() != 0) {
                    for (int i = 0; i < listNAMHOC.size(); i++) {
                        if (listNAMHOC.get(i).equals(resultSet.getString("NAMHOC"))) {
                            isPresent = true;
                            //System.out.println("Kiem tra");
                            break;
                        }
                    }
                    if (!isPresent) {
                        listNAMHOC.add(resultSet.getString("NAMHOC"));
                        //System.out.println("Kiem tra 1");
                        isPresent = false;
                    }
                } else {
                    listNAMHOC.add(resultSet.getString("NAMHOC"));
                    ///System.out.println("Kiem tra 2");
                }

            }
            if (!statement.isClosed()) {
                statement.close();
                System.out.println("Close SEARCH NAMHOC");
            }
            jcbSemester.addItem("1");
            jcbSemester.addItem("2");

            for (String item : listNAMHOC) {
                if (listNAMHOC == null) {
                    break;
                } else {
                    jcbYear.addItem(item);
                }
            }

        } catch (SQLException ex) {
            Logger.getLogger(TeacherSearchResultFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpTeacherGradingManagementNewSubjectPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jtfNewSubjectName = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jtfNewSubjectNote = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jtfNewSubjectProgressGrade = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jtfNewSubjectMidTermGrade = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jtfNewSubjectFinalTermScore = new javax.swing.JTextField();
        jbSaveNewSubject = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jlbAddSubjectFor = new javax.swing.JLabel();
        jbBack = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jcbSemester = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jcbYear = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jpTeacherGradingManagementNewSubjectPanel.setBackground(new java.awt.Color(255, 255, 255));
        jpTeacherGradingManagementNewSubjectPanel.setForeground(new java.awt.Color(255, 255, 255));
        jpTeacherGradingManagementNewSubjectPanel.setPreferredSize(new java.awt.Dimension(785, 540));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Tên môn học:");

        jtfNewSubjectName.setBackground(new java.awt.Color(217, 217, 217));
        jtfNewSubjectName.setForeground(new java.awt.Color(153, 153, 153));
        jtfNewSubjectName.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jtfNewSubjectName.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtfNewSubjectNameMouseClicked(evt);
            }
        });
        jtfNewSubjectName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfNewSubjectNameActionPerformed(evt);
            }
        });

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Ghi chú (nếu có):");

        jtfNewSubjectNote.setBackground(new java.awt.Color(217, 217, 217));
        jtfNewSubjectNote.setForeground(new java.awt.Color(153, 153, 153));
        jtfNewSubjectNote.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jtfNewSubjectNote.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtfNewSubjectNoteMouseClicked(evt);
            }
        });
        jtfNewSubjectNote.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfNewSubjectNoteActionPerformed(evt);
            }
        });

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Điểm QT");

        jtfNewSubjectProgressGrade.setBackground(new java.awt.Color(217, 217, 217));
        jtfNewSubjectProgressGrade.setForeground(new java.awt.Color(153, 153, 153));
        jtfNewSubjectProgressGrade.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jtfNewSubjectProgressGrade.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtfNewSubjectProgressGradeMouseClicked(evt);
            }
        });
        jtfNewSubjectProgressGrade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfNewSubjectProgressGradeActionPerformed(evt);
            }
        });

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Điểm GK");

        jtfNewSubjectMidTermGrade.setBackground(new java.awt.Color(217, 217, 217));
        jtfNewSubjectMidTermGrade.setForeground(new java.awt.Color(153, 153, 153));
        jtfNewSubjectMidTermGrade.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jtfNewSubjectMidTermGrade.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtfNewSubjectMidTermGradeMouseClicked(evt);
            }
        });
        jtfNewSubjectMidTermGrade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfNewSubjectMidTermGradeActionPerformed(evt);
            }
        });

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Điểm CK");

        jtfNewSubjectFinalTermScore.setBackground(new java.awt.Color(217, 217, 217));
        jtfNewSubjectFinalTermScore.setForeground(new java.awt.Color(153, 153, 153));
        jtfNewSubjectFinalTermScore.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jtfNewSubjectFinalTermScore.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtfNewSubjectFinalTermScoreMouseClicked(evt);
            }
        });
        jtfNewSubjectFinalTermScore.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfNewSubjectFinalTermScoreActionPerformed(evt);
            }
        });

        jbSaveNewSubject.setBackground(new java.awt.Color(169, 186, 247));
        jbSaveNewSubject.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jbSaveNewSubject.setForeground(new java.awt.Color(255, 255, 255));
        jbSaveNewSubject.setText("Thêm");
        jbSaveNewSubject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSaveNewSubjectActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(102, 255, 255));
        jPanel2.setForeground(new java.awt.Color(51, 255, 255));

        jlbAddSubjectFor.setBackground(new java.awt.Color(0, 0, 0));
        jlbAddSubjectFor.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jlbAddSubjectFor.setForeground(new java.awt.Color(255, 255, 255));
        jlbAddSubjectFor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbAddSubjectFor.setText("THÊM MÔN HỌC");

        jbBack.setBackground(new java.awt.Color(153, 204, 255));
        jbBack.setForeground(new java.awt.Color(255, 255, 255));
        jbBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/studentgradingmanager/images/icon-back-48.png"))); // NOI18N
        jbBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jbBack, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(96, 96, 96)
                .addComponent(jlbAddSubjectFor, javax.swing.GroupLayout.PREFERRED_SIZE, 589, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jbBack, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jlbAddSubjectFor, javax.swing.GroupLayout.DEFAULT_SIZE, 61, Short.MAX_VALUE))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("Học kỳ");

        jcbSemester.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jcbSemesterItemStateChanged(evt);
            }
        });

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setText("Năm học");

        javax.swing.GroupLayout jpTeacherGradingManagementNewSubjectPanelLayout = new javax.swing.GroupLayout(jpTeacherGradingManagementNewSubjectPanel);
        jpTeacherGradingManagementNewSubjectPanel.setLayout(jpTeacherGradingManagementNewSubjectPanelLayout);
        jpTeacherGradingManagementNewSubjectPanelLayout.setHorizontalGroup(
            jpTeacherGradingManagementNewSubjectPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpTeacherGradingManagementNewSubjectPanelLayout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jpTeacherGradingManagementNewSubjectPanelLayout.createSequentialGroup()
                .addGap(158, 158, 158)
                .addGroup(jpTeacherGradingManagementNewSubjectPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpTeacherGradingManagementNewSubjectPanelLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jtfNewSubjectProgressGrade, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jtfNewSubjectMidTermGrade, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(jLabel5)
                        .addGap(28, 28, 28)
                        .addComponent(jtfNewSubjectFinalTermScore, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(282, Short.MAX_VALUE))
                    .addGroup(jpTeacherGradingManagementNewSubjectPanelLayout.createSequentialGroup()
                        .addGroup(jpTeacherGradingManagementNewSubjectPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpTeacherGradingManagementNewSubjectPanelLayout.createSequentialGroup()
                                .addGroup(jpTeacherGradingManagementNewSubjectPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jpTeacherGradingManagementNewSubjectPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jtfNewSubjectName, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jtfNewSubjectNote, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jpTeacherGradingManagementNewSubjectPanelLayout.createSequentialGroup()
                                .addGroup(jpTeacherGradingManagementNewSubjectPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jcbSemester, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jpTeacherGradingManagementNewSubjectPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(jcbYear, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(177, 177, 177)))
                        .addComponent(jbSaveNewSubject, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(66, 66, 66))))
        );
        jpTeacherGradingManagementNewSubjectPanelLayout.setVerticalGroup(
            jpTeacherGradingManagementNewSubjectPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpTeacherGradingManagementNewSubjectPanelLayout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpTeacherGradingManagementNewSubjectPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jtfNewSubjectName, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jpTeacherGradingManagementNewSubjectPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jpTeacherGradingManagementNewSubjectPanelLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jbSaveNewSubject, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpTeacherGradingManagementNewSubjectPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jpTeacherGradingManagementNewSubjectPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jtfNewSubjectNote, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                        .addGroup(jpTeacherGradingManagementNewSubjectPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jpTeacherGradingManagementNewSubjectPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jcbYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jcbSemester, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(44, 44, 44)
                .addGroup(jpTeacherGradingManagementNewSubjectPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfNewSubjectProgressGrade, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jtfNewSubjectMidTermGrade, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jtfNewSubjectFinalTermScore, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(197, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpTeacherGradingManagementNewSubjectPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 960, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpTeacherGradingManagementNewSubjectPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtfNewSubjectNameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtfNewSubjectNameMouseClicked
        if (jtfNewSubjectName.getText().equals("Nhập tên môn học...")) {
            jtfNewSubjectName.setText("");
        }
    }//GEN-LAST:event_jtfNewSubjectNameMouseClicked

    private void jtfNewSubjectNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfNewSubjectNameActionPerformed

    }//GEN-LAST:event_jtfNewSubjectNameActionPerformed

    private void jtfNewSubjectNoteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtfNewSubjectNoteMouseClicked
        if (jtfNewSubjectNote.getText().equals("Nhập ghi chú...")) {
            jtfNewSubjectNote.setText("");
        }
    }//GEN-LAST:event_jtfNewSubjectNoteMouseClicked

    private void jtfNewSubjectNoteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfNewSubjectNoteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfNewSubjectNoteActionPerformed

    private void jtfNewSubjectProgressGradeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtfNewSubjectProgressGradeMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfNewSubjectProgressGradeMouseClicked

    private void jtfNewSubjectProgressGradeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfNewSubjectProgressGradeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfNewSubjectProgressGradeActionPerformed

    private void jtfNewSubjectMidTermGradeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtfNewSubjectMidTermGradeMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfNewSubjectMidTermGradeMouseClicked

    private void jtfNewSubjectMidTermGradeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfNewSubjectMidTermGradeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfNewSubjectMidTermGradeActionPerformed

    private void jtfNewSubjectFinalTermScoreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtfNewSubjectFinalTermScoreMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfNewSubjectFinalTermScoreMouseClicked

    private void jtfNewSubjectFinalTermScoreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfNewSubjectFinalTermScoreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfNewSubjectFinalTermScoreActionPerformed

    private void jbSaveNewSubjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSaveNewSubjectActionPerformed
        // TODO add your handling code here:
        try {
            updateDB();

            MessageBroker.getInstance().sendMessage("Data mon hoc");
            dispose();

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_jbSaveNewSubjectActionPerformed
    private void updateDB() {
        System.err.println("Chay upate");
        if (jtfNewSubjectName.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Vui Lòng Điền Tên Môn Học");
        } else {
            try {
                String fullMon = jtfNewSubjectName.getText().toString().trim();
                String[] tachTungTu = fullMon.split(" ");
                String maMHNew = "";
                for (String item : tachTungTu) {
                    maMHNew += item.substring(0, 1).toUpperCase();
                }
                maMHNew += studentBase.getMALOP().substring(1, 2);
                System.err.println(maMHNew);

                java.sql.Connection connection = DBConnect.getConnection();
                //JOptionPane.showMessageDialog(this, "Xin chào giáo viên " + matkGV);

                String checkSql = "SELECT MAMH FROM MONHOC WHERE MAMH = ?";
                PreparedStatement checkStatement = connection.prepareStatement(checkSql);
                checkStatement.setString(1, maMHNew);
                ResultSet _resultSet = checkStatement.executeQuery();

                if (_resultSet.next()) {
                    JOptionPane.showMessageDialog(null, maMHNew + " Đã tồn tại không thể thêm mới môn này!");
                } else {
                    // them mon hoc moi
                    String sql = "INSERT INTO MONHOC VALUES (?, ?)";
                    PreparedStatement statement = connection.prepareStatement(sql);
                    statement.setString(1, maMHNew);
                    statement.setString(2, fullMon.toUpperCase());

                    int rowsInserted = statement.executeUpdate();

                    if (rowsInserted > 0) {
                        System.out.println("Dữ liệu môn học đã được thêm thành công vào cơ sở dữ liệu.");
                    }

                    sql = "INSERT INTO DIEM VALUES (?, ?, ?, ?, ?, ?, ?, ?)";
                    statement = connection.prepareCall(sql);

                    String ghichu = jtfNewSubjectNote.getText().toString().trim();
                    String mahk;
                    if (jcbSemester.getSelectedItem().equals("1")) {
                        mahk = "HK01";
                    } else {
                        mahk = "HK02";
                    }

                    String namhoc = jcbYear.getSelectedItem().toString();

                    String diemQT = !jtfNewSubjectProgressGrade.getText().toString().trim().isEmpty() ? jtfNewSubjectProgressGrade.getText().toString().trim() : "";

                    String diemGk = !jtfNewSubjectMidTermGrade.getText().toString().trim().isEmpty() ? jtfNewSubjectMidTermGrade.getText().toString().toString().trim() : "";

                    String diemCK = !jtfNewSubjectFinalTermScore.getText().toString().trim().isEmpty() ? jtfNewSubjectFinalTermScore.getText().toString().toString().trim() : "";

                    String diemTBHK = !diemQT.equals("") || !diemGk.equals("") || !diemCK.equals("")
                            ? String.valueOf((Double.valueOf(diemGk) + Double.valueOf(diemQT) + Double.valueOf(diemCK)) / 3) : "";

                    System.err.println(jtfNewSubjectProgressGrade.getText().toString().trim());

                    statement.setString(1, maMHNew);
                    statement.setString(2, studentBase.getMAHS());
                    statement.setString(3, diemQT);
                    statement.setString(4, diemGk);
                    statement.setString(5, diemCK);
                    statement.setString(6, diemTBHK);
                    statement.setString(7, ghichu);
                    statement.setString(8, mahk);

                    rowsInserted = statement.executeUpdate();

                    if (rowsInserted > 0) {
                        System.err.println("Thêm Điểm Và Môn Học Thành Công");
                    }
                    System.err.println(maMHNew + " " + studentBase.getMAHS() + " " + diemQT + " " + diemGk + " " + diemCK + " " + diemTBHK + " " + ghichu + " " + mahk);
                    statement.close();
                }

                checkStatement.close();
                connection.close();

            } catch (SQLException ex) {
                Logger.getLogger(TeacherGradingManagementNewSubjectFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }
    private void jbBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbBackActionPerformed
        dispose();
    }//GEN-LAST:event_jbBackActionPerformed

    private void jcbSemesterItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jcbSemesterItemStateChanged
        // TODO add your handling code here:

    }//GEN-LAST:event_jcbSemesterItemStateChanged

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton jbBack;
    private javax.swing.JButton jbSaveNewSubject;
    private javax.swing.JComboBox<String> jcbSemester;
    private javax.swing.JComboBox<String> jcbYear;
    private javax.swing.JLabel jlbAddSubjectFor;
    private javax.swing.JPanel jpTeacherGradingManagementNewSubjectPanel;
    private javax.swing.JTextField jtfNewSubjectFinalTermScore;
    private javax.swing.JTextField jtfNewSubjectMidTermGrade;
    private javax.swing.JTextField jtfNewSubjectName;
    private javax.swing.JTextField jtfNewSubjectNote;
    private javax.swing.JTextField jtfNewSubjectProgressGrade;
    // End of variables declaration//GEN-END:variables
}
