/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package studentgradingmanager.UI.teacher.jpanel;

import java.awt.BorderLayout;
import javax.swing.JPanel;
import studentgradingmanager.controller.TeacherGradingManagementController;

/**
 *
 * @author Quan
 */
public class TeacherGradingManagement extends javax.swing.JPanel {

    /**
     * Creates new form TeacherGradingManagement
     */
    public TeacherGradingManagement() {
        initComponents();
        setLayout(new BorderLayout());
        TeacherGradingManagementController controller = new TeacherGradingManagementController(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpTeacherGradingManagement = new javax.swing.JPanel();

        setBackground(new java.awt.Color(255, 255, 255));
        setForeground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(785, 540));

        jpTeacherGradingManagement.setBackground(new java.awt.Color(255, 255, 255));
        jpTeacherGradingManagement.setForeground(new java.awt.Color(255, 255, 255));
        jpTeacherGradingManagement.setPreferredSize(new java.awt.Dimension(785, 540));
        jpTeacherGradingManagement.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpTeacherGradingManagement, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpTeacherGradingManagement, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jpTeacherGradingManagement;
    // End of variables declaration//GEN-END:variables
}
