/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package studentgradingmanager.UI.teacher.jpanel;

import Database.DBConnect;
import OOP.CapNhatDiem;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;

import Database.DBConnect;
import OOP.CapNhatDiem;
import OOP.DIEM;
import OOP.StudentBase;
import TransferData.MessageBroker;
import TransferData.MessageListener;
import java.awt.Color;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Quan
 */
public class TeacherGradingManagementUpdateSubjectFrame extends javax.swing.JFrame {

    private CapNhatDiem data;

    /**
     * Creates new form TeacherGradingManagementUpdateSubjectFrame
     */
    public TeacherGradingManagementUpdateSubjectFrame(CapNhatDiem data) {
        initComponents();
        this.data = data;

        System.err.println(data.toString());

        mirrorData();

        this.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
        this.addWindowListener(new WindowAdapter() {
            public void windowClosing(WindowEvent e) {
                dispose();
            }
        });
    }

    private void mirrorData() {
        CapNhatDiem item = data;
        jLabel1.setText("CHỈNH SỬA MÔN HỌC " + data.getTenHS());
        jcbSubjects.addItem(data.getTenMH());
        jtfNewSubjectProgressGrade.setText(data.getDiemQT());
        jtfNewSubjectMidTermGrade.setText(data.getDiemGK());
        jtfNewSubjectFinalTermScore.setText(data.getDiemCK());
        jtfNewNote.setText(data.getGhichu());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpTeacherGradingManagementEditSubjectPanel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jtfNewSubjectProgressGrade = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jtfNewSubjectMidTermGrade = new javax.swing.JTextField();
        jtfNewSubjectFinalTermScore = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jbSaveEditSubject = new javax.swing.JButton();
        jcbSubjects = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jbBack = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jtfNewNote = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jpTeacherGradingManagementEditSubjectPanel.setBackground(new java.awt.Color(255, 255, 255));
        jpTeacherGradingManagementEditSubjectPanel.setForeground(new java.awt.Color(255, 255, 255));
        jpTeacherGradingManagementEditSubjectPanel.setPreferredSize(new java.awt.Dimension(785, 540));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Điểm QT");

        jtfNewSubjectProgressGrade.setBackground(new java.awt.Color(217, 217, 217));
        jtfNewSubjectProgressGrade.setForeground(new java.awt.Color(153, 153, 153));
        jtfNewSubjectProgressGrade
                .setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jtfNewSubjectProgressGrade.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtfNewSubjectProgressGradeMouseClicked(evt);
            }
        });
        jtfNewSubjectProgressGrade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfNewSubjectProgressGradeActionPerformed(evt);
            }
        });

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Điểm GK");

        jtfNewSubjectMidTermGrade.setBackground(new java.awt.Color(217, 217, 217));
        jtfNewSubjectMidTermGrade.setForeground(new java.awt.Color(153, 153, 153));
        jtfNewSubjectMidTermGrade
                .setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jtfNewSubjectMidTermGrade.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtfNewSubjectMidTermGradeMouseClicked(evt);
            }
        });
        jtfNewSubjectMidTermGrade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfNewSubjectMidTermGradeActionPerformed(evt);
            }
        });

        jtfNewSubjectFinalTermScore.setBackground(new java.awt.Color(217, 217, 217));
        jtfNewSubjectFinalTermScore.setForeground(new java.awt.Color(153, 153, 153));
        jtfNewSubjectFinalTermScore
                .setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jtfNewSubjectFinalTermScore.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtfNewSubjectFinalTermScoreMouseClicked(evt);
            }
        });
        jtfNewSubjectFinalTermScore.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfNewSubjectFinalTermScoreActionPerformed(evt);
            }
        });

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Điểm CK");

        jbSaveEditSubject.setBackground(new java.awt.Color(169, 186, 247));
        jbSaveEditSubject.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jbSaveEditSubject.setForeground(new java.awt.Color(255, 255, 255));
        jbSaveEditSubject.setText("Cập nhật");
        jbSaveEditSubject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSaveEditSubjectActionPerformed(evt);
            }
        });

        jcbSubjects.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Môn học");

        jPanel1.setBackground(new java.awt.Color(102, 255, 255));
        jPanel1.setForeground(new java.awt.Color(51, 255, 255));

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("CHỈNH SỬA MÔN HỌC");

        jbBack.setBackground(new java.awt.Color(255, 51, 51));
        jbBack.setForeground(new java.awt.Color(255, 255, 255));
        jbBack.setIcon(
                new javax.swing.ImageIcon(getClass().getResource("/studentgradingmanager/images/icon-exit-48.png"))); // NOI18N
        jbBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(149, 149, 149)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 679,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jbBack, javax.swing.GroupLayout.PREFERRED_SIZE, 40,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(33, 33, 33)));
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 61,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(11, 11, 11)
                                                .addComponent(jbBack, javax.swing.GroupLayout.PREFERRED_SIZE, 41,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap(20, Short.MAX_VALUE)));

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("Ghi Chú");

        jtfNewNote.setBackground(new java.awt.Color(217, 217, 217));
        jtfNewNote.setForeground(new java.awt.Color(153, 153, 153));
        jtfNewNote.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jtfNewNote.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtfNewNoteMouseClicked(evt);
            }
        });
        jtfNewNote.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfNewNoteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpTeacherGradingManagementEditSubjectPanelLayout = new javax.swing.GroupLayout(
                jpTeacherGradingManagementEditSubjectPanel);
        jpTeacherGradingManagementEditSubjectPanel.setLayout(jpTeacherGradingManagementEditSubjectPanelLayout);
        jpTeacherGradingManagementEditSubjectPanelLayout.setHorizontalGroup(
                jpTeacherGradingManagementEditSubjectPanelLayout
                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jpTeacherGradingManagementEditSubjectPanelLayout.createSequentialGroup()
                                .addGap(150, 150, 150)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jcbSubjects, javax.swing.GroupLayout.PREFERRED_SIZE, 137,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                                jpTeacherGradingManagementEditSubjectPanelLayout.createSequentialGroup()
                                        .addContainerGap(153, Short.MAX_VALUE)
                                        .addGroup(jpTeacherGradingManagementEditSubjectPanelLayout
                                                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addGroup(jpTeacherGradingManagementEditSubjectPanelLayout
                                                        .createSequentialGroup()
                                                        .addComponent(jLabel7)
                                                        .addGap(18, 18, 18)
                                                        .addComponent(jtfNewNote))
                                                .addGroup(jpTeacherGradingManagementEditSubjectPanelLayout
                                                        .createSequentialGroup()
                                                        .addComponent(jLabel3)
                                                        .addPreferredGap(
                                                                javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                        .addComponent(jtfNewSubjectProgressGrade,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE, 77,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(18, 18, 18)
                                                        .addComponent(jLabel4)
                                                        .addPreferredGap(
                                                                javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                        .addComponent(jtfNewSubjectMidTermGrade,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE, 77,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(33, 33, 33)
                                                        .addComponent(jLabel5)
                                                        .addPreferredGap(
                                                                javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                        .addComponent(jtfNewSubjectFinalTermScore,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE, 77,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(63, 63, 63)
                                        .addComponent(jbSaveEditSubject, javax.swing.GroupLayout.PREFERRED_SIZE, 100,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(153, 153, 153)));
        jpTeacherGradingManagementEditSubjectPanelLayout.setVerticalGroup(
                jpTeacherGradingManagementEditSubjectPanelLayout
                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jpTeacherGradingManagementEditSubjectPanelLayout.createSequentialGroup()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(jpTeacherGradingManagementEditSubjectPanelLayout
                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jcbSubjects, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel6))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21,
                                        Short.MAX_VALUE)
                                .addGroup(jpTeacherGradingManagementEditSubjectPanelLayout
                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jtfNewSubjectProgressGrade,
                                                javax.swing.GroupLayout.PREFERRED_SIZE, 34,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel3)
                                        .addComponent(jLabel4)
                                        .addComponent(jtfNewSubjectMidTermGrade, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel5)
                                        .addComponent(jtfNewSubjectFinalTermScore,
                                                javax.swing.GroupLayout.PREFERRED_SIZE, 34,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jbSaveEditSubject))
                                .addGap(18, 18, 18)
                                .addGroup(jpTeacherGradingManagementEditSubjectPanelLayout
                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel7)
                                        .addComponent(jtfNewNote, javax.swing.GroupLayout.PREFERRED_SIZE, 34,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(290, 290, 290)));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jpTeacherGradingManagementEditSubjectPanel, javax.swing.GroupLayout.DEFAULT_SIZE,
                                960, Short.MAX_VALUE));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jpTeacherGradingManagementEditSubjectPanel, javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtfNewSubjectProgressGradeMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_jtfNewSubjectProgressGradeMouseClicked
        // TODO add your handling code here:
    }// GEN-LAST:event_jtfNewSubjectProgressGradeMouseClicked

    private void jtfNewSubjectProgressGradeActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jtfNewSubjectProgressGradeActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_jtfNewSubjectProgressGradeActionPerformed

    private void jtfNewSubjectMidTermGradeMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_jtfNewSubjectMidTermGradeMouseClicked
        // TODO add your handling code here:
    }// GEN-LAST:event_jtfNewSubjectMidTermGradeMouseClicked

    private void jtfNewSubjectMidTermGradeActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jtfNewSubjectMidTermGradeActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_jtfNewSubjectMidTermGradeActionPerformed

    private void jtfNewSubjectFinalTermScoreMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_jtfNewSubjectFinalTermScoreMouseClicked
        // TODO add your handling code here:
    }// GEN-LAST:event_jtfNewSubjectFinalTermScoreMouseClicked

    private void jtfNewSubjectFinalTermScoreActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jtfNewSubjectFinalTermScoreActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_jtfNewSubjectFinalTermScoreActionPerformed

    private void jbSaveEditSubjectActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jbSaveEditSubjectActionPerformed
        try {
            // TODO add your handling code here:

            System.err.println(jtfNewSubjectProgressGrade.getText().trim() + "-"
                    + jtfNewSubjectMidTermGrade.getText().trim() + "-" + jtfNewSubjectFinalTermScore.getText().trim());
            System.err.println(data.getMaMH());
            // cap nhat
            java.sql.Connection connection = DBConnect.getConnection();
            // JOptionPane.showMessageDialog(this, "Xin chào giáo viên " + matkGV);
            String sql = "UPDATE DIEM SET DIEMQT = ?, DIEMGK = ?, DIEMCK = ?, GHICHU = ? WHERE MAHS = ? AND MAHK = ? AND MAMH = ?";
            PreparedStatement statement = connection.prepareStatement(sql);
            statement.setString(1, jtfNewSubjectProgressGrade.getText().trim());
            statement.setString(2, jtfNewSubjectMidTermGrade.getText().trim());
            statement.setString(3, jtfNewSubjectFinalTermScore.getText().trim());
            statement.setString(4, jtfNewNote.getText().trim());
            statement.setString(5, data.getMaHS());
            System.err.println(data.getHocki());
            if (data.getHocki().equals("1")) {
                statement.setString(6, "HK01");
            } else if (data.getHocki().equals("2")) {
                statement.setString(6, "HK02");
            }
            statement.setString(7, data.getMaMH());
            int rowsAffected = statement.executeUpdate();
            if (rowsAffected > 0) {
                System.out.println("Cập nhật thành công.");
                JOptionPane.showMessageDialog(this, "Cập nhật thành công.");
                MessageBroker.getInstance().sendMessage("Data mon hoc");
                dispose();
            } else {
                System.out.println("Có lỗi xảy ra khi cập nhật.");
                JOptionPane.showMessageDialog(this, "Có lỗi xảy ra khi cập nhật.");
                dispose();
            }

        } catch (SQLException ex) {
            Logger.getLogger(TeacherGradingManagementUpdateSubjectFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }// GEN-LAST:event_jbSaveEditSubjectActionPerformed

    private void jbBackActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jbBackActionPerformed
        dispose();
    }// GEN-LAST:event_jbBackActionPerformed

    private void jtfNewNoteMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_jtfNewNoteMouseClicked
        // TODO add your handling code here:
    }// GEN-LAST:event_jtfNewNoteMouseClicked

    private void jtfNewNoteActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jtfNewNoteActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_jtfNewNoteActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbBack;
    private javax.swing.JButton jbSaveEditSubject;
    private javax.swing.JComboBox<String> jcbSubjects;
    private javax.swing.JPanel jpTeacherGradingManagementEditSubjectPanel;
    private javax.swing.JTextField jtfNewNote;
    private javax.swing.JTextField jtfNewSubjectFinalTermScore;
    private javax.swing.JTextField jtfNewSubjectMidTermGrade;
    private javax.swing.JTextField jtfNewSubjectProgressGrade;
    // End of variables declaration//GEN-END:variables
}
