/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package studentgradingmanager.UI.teacher.jpanel;


import OOP.Teacher;
import TransferData.MessageListener;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import studentgradingmanager.controller.TeacherSearchController;

/**
 *
 * @author Quan
 */
public class TeacherSearch extends javax.swing.JPanel {
    private Teacher teacherItem;
    /**
     * Creates new form TeacherSearch
     */
    
    public TeacherSearch(Teacher teacherItem) {
        initComponents();
        this.teacherItem = teacherItem;
        TeacherSearchController controller = new TeacherSearchController(this, teacherItem);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpTeacherSearch = new javax.swing.JPanel();

        jpTeacherSearch.setBackground(new java.awt.Color(255, 255, 255));
        jpTeacherSearch.setForeground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jpTeacherSearchLayout = new javax.swing.GroupLayout(jpTeacherSearch);
        jpTeacherSearch.setLayout(jpTeacherSearchLayout);
        jpTeacherSearchLayout.setHorizontalGroup(
            jpTeacherSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 760, Short.MAX_VALUE)
        );
        jpTeacherSearchLayout.setVerticalGroup(
            jpTeacherSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 540, Short.MAX_VALUE)
        );

        setBackground(new java.awt.Color(255, 255, 255));
        setForeground(new java.awt.Color(255, 255, 255));
        setLayout(new java.awt.BorderLayout());
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jpTeacherSearch;
    // End of variables declaration//GEN-END:variables

    
}
