/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package studentgradingmanager.UI.teacher.jpanel;

import OOP.StudentBase;

/**
 *
 * @author Quan
 */
public class TeacherSearchNewSubjectFrame extends javax.swing.JFrame {
    /**
     * Creates new form TeacherGradingManagementNewSubjectFrame
     */
    public TeacherSearchNewSubjectFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpTeacherGradingManagementNewSubjectPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jtfNewSubjectName = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jtfNewSubjectNote = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jtfNewSubjectProgressGrade = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jtfNewSubjectMidTermGrade = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jtfNewSubjectFinalTermScore = new javax.swing.JTextField();
        jbSaveNewSubject = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jAddSubjectFor = new javax.swing.JLabel();
        jbExit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jpTeacherGradingManagementNewSubjectPanel.setBackground(new java.awt.Color(255, 255, 255));
        jpTeacherGradingManagementNewSubjectPanel.setForeground(new java.awt.Color(255, 255, 255));
        jpTeacherGradingManagementNewSubjectPanel.setPreferredSize(new java.awt.Dimension(960, 540));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Tên môn học:");

        jtfNewSubjectName.setBackground(new java.awt.Color(217, 217, 217));
        jtfNewSubjectName.setForeground(new java.awt.Color(153, 153, 153));
        jtfNewSubjectName.setText("Nhập tên môn học...");
        jtfNewSubjectName.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jtfNewSubjectName.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtfNewSubjectNameMouseClicked(evt);
            }
        });
        jtfNewSubjectName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfNewSubjectNameActionPerformed(evt);
            }
        });

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Ghi chú (nếu có):");

        jtfNewSubjectNote.setBackground(new java.awt.Color(217, 217, 217));
        jtfNewSubjectNote.setForeground(new java.awt.Color(153, 153, 153));
        jtfNewSubjectNote.setText("Nhập ghi chú...");
        jtfNewSubjectNote.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jtfNewSubjectNote.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtfNewSubjectNoteMouseClicked(evt);
            }
        });
        jtfNewSubjectNote.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfNewSubjectNoteActionPerformed(evt);
            }
        });

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Điểm QT");

        jtfNewSubjectProgressGrade.setBackground(new java.awt.Color(217, 217, 217));
        jtfNewSubjectProgressGrade.setForeground(new java.awt.Color(153, 153, 153));
        jtfNewSubjectProgressGrade.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jtfNewSubjectProgressGrade.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtfNewSubjectProgressGradeMouseClicked(evt);
            }
        });
        jtfNewSubjectProgressGrade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfNewSubjectProgressGradeActionPerformed(evt);
            }
        });

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Điểm GK");

        jtfNewSubjectMidTermGrade.setBackground(new java.awt.Color(217, 217, 217));
        jtfNewSubjectMidTermGrade.setForeground(new java.awt.Color(153, 153, 153));
        jtfNewSubjectMidTermGrade.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jtfNewSubjectMidTermGrade.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtfNewSubjectMidTermGradeMouseClicked(evt);
            }
        });
        jtfNewSubjectMidTermGrade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfNewSubjectMidTermGradeActionPerformed(evt);
            }
        });

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Điểm CK");

        jtfNewSubjectFinalTermScore.setBackground(new java.awt.Color(217, 217, 217));
        jtfNewSubjectFinalTermScore.setForeground(new java.awt.Color(153, 153, 153));
        jtfNewSubjectFinalTermScore.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jtfNewSubjectFinalTermScore.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtfNewSubjectFinalTermScoreMouseClicked(evt);
            }
        });
        jtfNewSubjectFinalTermScore.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfNewSubjectFinalTermScoreActionPerformed(evt);
            }
        });

        jbSaveNewSubject.setBackground(new java.awt.Color(169, 186, 247));
        jbSaveNewSubject.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jbSaveNewSubject.setForeground(new java.awt.Color(255, 255, 255));
        jbSaveNewSubject.setText("Thêm");
        jbSaveNewSubject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSaveNewSubjectActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(102, 255, 255));
        jPanel2.setForeground(new java.awt.Color(51, 255, 255));

        jAddSubjectFor.setBackground(new java.awt.Color(0, 0, 0));
        jAddSubjectFor.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jAddSubjectFor.setForeground(new java.awt.Color(255, 255, 255));
        jAddSubjectFor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jAddSubjectFor.setText("THÊM MÔN HỌC");

        jbExit.setBackground(new java.awt.Color(255, 51, 51));
        jbExit.setForeground(new java.awt.Color(255, 255, 255));
        jbExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/studentgradingmanager/images/icon-exit-48.png"))); // NOI18N
        jbExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(334, 334, 334)
                .addComponent(jAddSubjectFor, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbExit, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jAddSubjectFor, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jbExit, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jpTeacherGradingManagementNewSubjectPanelLayout = new javax.swing.GroupLayout(jpTeacherGradingManagementNewSubjectPanel);
        jpTeacherGradingManagementNewSubjectPanel.setLayout(jpTeacherGradingManagementNewSubjectPanelLayout);
        jpTeacherGradingManagementNewSubjectPanelLayout.setHorizontalGroup(
            jpTeacherGradingManagementNewSubjectPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpTeacherGradingManagementNewSubjectPanelLayout.createSequentialGroup()
                .addGap(0, 140, Short.MAX_VALUE)
                .addGroup(jpTeacherGradingManagementNewSubjectPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jpTeacherGradingManagementNewSubjectPanelLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jtfNewSubjectProgressGrade, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jtfNewSubjectMidTermGrade, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(jLabel5)
                        .addGap(28, 28, 28)
                        .addComponent(jtfNewSubjectFinalTermScore, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(297, 297, 297))
                    .addGroup(jpTeacherGradingManagementNewSubjectPanelLayout.createSequentialGroup()
                        .addGroup(jpTeacherGradingManagementNewSubjectPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jpTeacherGradingManagementNewSubjectPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jtfNewSubjectName, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtfNewSubjectNote, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbSaveNewSubject, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(126, 126, 126))))
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jpTeacherGradingManagementNewSubjectPanelLayout.setVerticalGroup(
            jpTeacherGradingManagementNewSubjectPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpTeacherGradingManagementNewSubjectPanelLayout.createSequentialGroup()
                .addGroup(jpTeacherGradingManagementNewSubjectPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpTeacherGradingManagementNewSubjectPanelLayout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(63, 63, 63)
                        .addGroup(jpTeacherGradingManagementNewSubjectPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jtfNewSubjectName, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jpTeacherGradingManagementNewSubjectPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jtfNewSubjectNote, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jpTeacherGradingManagementNewSubjectPanelLayout.createSequentialGroup()
                        .addGap(187, 187, 187)
                        .addComponent(jbSaveNewSubject, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(21, 21, 21)
                .addGroup(jpTeacherGradingManagementNewSubjectPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfNewSubjectProgressGrade, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jtfNewSubjectMidTermGrade, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jtfNewSubjectFinalTermScore, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(251, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpTeacherGradingManagementNewSubjectPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpTeacherGradingManagementNewSubjectPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtfNewSubjectNameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtfNewSubjectNameMouseClicked
        if (jtfNewSubjectName.getText().equals("Nhập tên môn học...")) {
            jtfNewSubjectName.setText("");
        }
    }//GEN-LAST:event_jtfNewSubjectNameMouseClicked

    private void jtfNewSubjectNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfNewSubjectNameActionPerformed

    }//GEN-LAST:event_jtfNewSubjectNameActionPerformed

    private void jtfNewSubjectNoteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtfNewSubjectNoteMouseClicked
        if (jtfNewSubjectNote.getText().equals("Nhập ghi chú...")) {
            jtfNewSubjectNote.setText("");
        }
    }//GEN-LAST:event_jtfNewSubjectNoteMouseClicked

    private void jtfNewSubjectNoteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfNewSubjectNoteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfNewSubjectNoteActionPerformed

    private void jtfNewSubjectProgressGradeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtfNewSubjectProgressGradeMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfNewSubjectProgressGradeMouseClicked

    private void jtfNewSubjectProgressGradeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfNewSubjectProgressGradeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfNewSubjectProgressGradeActionPerformed

    private void jtfNewSubjectMidTermGradeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtfNewSubjectMidTermGradeMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfNewSubjectMidTermGradeMouseClicked

    private void jtfNewSubjectMidTermGradeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfNewSubjectMidTermGradeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfNewSubjectMidTermGradeActionPerformed

    private void jtfNewSubjectFinalTermScoreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtfNewSubjectFinalTermScoreMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfNewSubjectFinalTermScoreMouseClicked

    private void jtfNewSubjectFinalTermScoreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfNewSubjectFinalTermScoreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfNewSubjectFinalTermScoreActionPerformed

    private void jbSaveNewSubjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSaveNewSubjectActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbSaveNewSubjectActionPerformed

    private void jbExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbExitActionPerformed
        dispose();
    }//GEN-LAST:event_jbExitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TeacherSearchNewSubjectFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TeacherSearchNewSubjectFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TeacherSearchNewSubjectFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TeacherSearchNewSubjectFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TeacherSearchNewSubjectFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jAddSubjectFor;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton jbExit;
    private javax.swing.JButton jbSaveNewSubject;
    private javax.swing.JPanel jpTeacherGradingManagementNewSubjectPanel;
    private javax.swing.JTextField jtfNewSubjectFinalTermScore;
    private javax.swing.JTextField jtfNewSubjectMidTermGrade;
    private javax.swing.JTextField jtfNewSubjectName;
    private javax.swing.JTextField jtfNewSubjectNote;
    private javax.swing.JTextField jtfNewSubjectProgressGrade;
    // End of variables declaration//GEN-END:variables
}