/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package studentgradingmanager.UI.teacher.jpanel;

import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author Quan
 */
public class TeacherGradingManagementUpdateSubjectPanel extends javax.swing.JPanel {

    public JLabel getjLabel3() {
        return jLabel3;
    }

    public void setjLabel3(JLabel jLabel3) {
        this.jLabel3 = jLabel3;
    }

    public JLabel getjLabel4() {
        return jLabel4;
    }

    public void setjLabel4(JLabel jLabel4) {
        this.jLabel4 = jLabel4;
    }

    public JLabel getjLabel5() {
        return jLabel5;
    }

    public void setjLabel5(JLabel jLabel5) {
        this.jLabel5 = jLabel5;
    }

    public JLabel getjLabel6() {
        return jLabel6;
    }

    public void setjLabel6(JLabel jLabel6) {
        this.jLabel6 = jLabel6;
    }

    public JButton getJbBack() {
        return jbBack;
    }

    public void setJbBack(JButton jbBack) {
        this.jbBack = jbBack;
    }

    public JButton getJbSaveEditSubject() {
        return jbSaveEditSubject;
    }

    public void setJbSaveEditSubject(JButton jbSaveEditSubject) {
        this.jbSaveEditSubject = jbSaveEditSubject;
    }

    public JComboBox<String> getJcbSubjects() {
        return jcbSubjects;
    }

    public void setJcbSubjects(JComboBox<String> jcbSubjects) {
        this.jcbSubjects = jcbSubjects;
    }

    public JPanel getJpTeacherGradingManagementEditSubjectPanel() {
        return jpTeacherGradingManagementEditSubjectPanel;
    }

    public void setJpTeacherGradingManagementEditSubjectPanel(JPanel jpTeacherGradingManagementEditSubjectPanel) {
        this.jpTeacherGradingManagementEditSubjectPanel = jpTeacherGradingManagementEditSubjectPanel;
    }

    public JTable getJtStudentResult() {
        return jtStudentResult;
    }

    public void setJtStudentResult(JTable jtStudentResult) {
        this.jtStudentResult = jtStudentResult;
    }

    public JTextField getJtfNewSubjectFinalTermScore() {
        return jtfNewSubjectFinalTermScore;
    }

    public void setJtfNewSubjectFinalTermScore(JTextField jtfNewSubjectFinalTermScore) {
        this.jtfNewSubjectFinalTermScore = jtfNewSubjectFinalTermScore;
    }

    public JTextField getJtfNewSubjectMidTermGrade() {
        return jtfNewSubjectMidTermGrade;
    }

    public void setJtfNewSubjectMidTermGrade(JTextField jtfNewSubjectMidTermGrade) {
        this.jtfNewSubjectMidTermGrade = jtfNewSubjectMidTermGrade;
    }

    public JTextField getJtfNewSubjectProgressGrade() {
        return jtfNewSubjectProgressGrade;
    }

    public void setJtfNewSubjectProgressGrade(JTextField jtfNewSubjectProgressGrade) {
        this.jtfNewSubjectProgressGrade = jtfNewSubjectProgressGrade;
    }

    /**
     * Creates new form TeacherGradingManagementEditSubjectPanel
     */
    public TeacherGradingManagementUpdateSubjectPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpTeacherGradingManagementEditSubjectPanel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jtfNewSubjectProgressGrade = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jtfNewSubjectMidTermGrade = new javax.swing.JTextField();
        jtfNewSubjectFinalTermScore = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jbSaveEditSubject = new javax.swing.JButton();
        jcbSubjects = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jbBack = new javax.swing.JButton();
        jsResult = new javax.swing.JScrollPane();
        jtStudentResult = new javax.swing.JTable();

        jpTeacherGradingManagementEditSubjectPanel.setBackground(new java.awt.Color(255, 255, 255));
        jpTeacherGradingManagementEditSubjectPanel.setForeground(new java.awt.Color(255, 255, 255));
        jpTeacherGradingManagementEditSubjectPanel.setPreferredSize(new java.awt.Dimension(785, 540));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Điểm QT");

        jtfNewSubjectProgressGrade.setBackground(new java.awt.Color(217, 217, 217));
        jtfNewSubjectProgressGrade.setForeground(new java.awt.Color(153, 153, 153));
        jtfNewSubjectProgressGrade.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jtfNewSubjectProgressGrade.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtfNewSubjectProgressGradeMouseClicked(evt);
            }
        });
        jtfNewSubjectProgressGrade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfNewSubjectProgressGradeActionPerformed(evt);
            }
        });

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Điểm GK");

        jtfNewSubjectMidTermGrade.setBackground(new java.awt.Color(217, 217, 217));
        jtfNewSubjectMidTermGrade.setForeground(new java.awt.Color(153, 153, 153));
        jtfNewSubjectMidTermGrade.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jtfNewSubjectMidTermGrade.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtfNewSubjectMidTermGradeMouseClicked(evt);
            }
        });
        jtfNewSubjectMidTermGrade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfNewSubjectMidTermGradeActionPerformed(evt);
            }
        });

        jtfNewSubjectFinalTermScore.setBackground(new java.awt.Color(217, 217, 217));
        jtfNewSubjectFinalTermScore.setForeground(new java.awt.Color(153, 153, 153));
        jtfNewSubjectFinalTermScore.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jtfNewSubjectFinalTermScore.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtfNewSubjectFinalTermScoreMouseClicked(evt);
            }
        });
        jtfNewSubjectFinalTermScore.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfNewSubjectFinalTermScoreActionPerformed(evt);
            }
        });

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Điểm CK");

        jbSaveEditSubject.setBackground(new java.awt.Color(169, 186, 247));
        jbSaveEditSubject.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jbSaveEditSubject.setForeground(new java.awt.Color(255, 255, 255));
        jbSaveEditSubject.setText("Cập nhật");
        jbSaveEditSubject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSaveEditSubjectActionPerformed(evt);
            }
        });

        jcbSubjects.setBackground(new java.awt.Color(255, 255, 255));
        jcbSubjects.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jcbSubjects.setForeground(new java.awt.Color(0, 0, 0));
        jcbSubjects.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Môn học");

        jbBack.setBackground(new java.awt.Color(153, 204, 255));
        jbBack.setForeground(new java.awt.Color(255, 255, 255));
        jbBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/studentgradingmanager/images/icon-back-48.png"))); // NOI18N

        jtStudentResult.setBackground(new java.awt.Color(255, 255, 255));
        jtStudentResult.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.black, java.awt.Color.black, java.awt.Color.black, java.awt.Color.black));
        jtStudentResult.setForeground(new java.awt.Color(0, 0, 0));
        jtStudentResult.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "STT", "Tên môn học", "Điểm QT", "Điểm GK", "Điểm CK", "Điểm TBHK", "Điểm TBNH", "Ghi chú"
            }
        ));
        jtStudentResult.setGridColor(new java.awt.Color(0, 0, 0));
        jtStudentResult.setShowGrid(true);
        jsResult.setViewportView(jtStudentResult);

        javax.swing.GroupLayout jpTeacherGradingManagementEditSubjectPanelLayout = new javax.swing.GroupLayout(jpTeacherGradingManagementEditSubjectPanel);
        jpTeacherGradingManagementEditSubjectPanel.setLayout(jpTeacherGradingManagementEditSubjectPanelLayout);
        jpTeacherGradingManagementEditSubjectPanelLayout.setHorizontalGroup(
            jpTeacherGradingManagementEditSubjectPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpTeacherGradingManagementEditSubjectPanelLayout.createSequentialGroup()
                .addGroup(jpTeacherGradingManagementEditSubjectPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpTeacherGradingManagementEditSubjectPanelLayout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addGroup(jpTeacherGradingManagementEditSubjectPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpTeacherGradingManagementEditSubjectPanelLayout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jtfNewSubjectProgressGrade, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jtfNewSubjectMidTermGrade, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(33, 33, 33)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jtfNewSubjectFinalTermScore, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(63, 63, 63)
                                .addComponent(jbSaveEditSubject, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jpTeacherGradingManagementEditSubjectPanelLayout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jcbSubjects, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jpTeacherGradingManagementEditSubjectPanelLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jbBack, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpTeacherGradingManagementEditSubjectPanelLayout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(jsResult, javax.swing.GroupLayout.PREFERRED_SIZE, 658, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(69, Short.MAX_VALUE))
        );
        jpTeacherGradingManagementEditSubjectPanelLayout.setVerticalGroup(
            jpTeacherGradingManagementEditSubjectPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpTeacherGradingManagementEditSubjectPanelLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jbBack, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(jpTeacherGradingManagementEditSubjectPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcbSubjects, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(jpTeacherGradingManagementEditSubjectPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfNewSubjectProgressGrade, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jtfNewSubjectMidTermGrade, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jtfNewSubjectFinalTermScore, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbSaveEditSubject))
                .addGap(29, 29, 29)
                .addComponent(jsResult, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpTeacherGradingManagementEditSubjectPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpTeacherGradingManagementEditSubjectPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jtfNewSubjectProgressGradeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtfNewSubjectProgressGradeMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfNewSubjectProgressGradeMouseClicked

    private void jtfNewSubjectProgressGradeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfNewSubjectProgressGradeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfNewSubjectProgressGradeActionPerformed

    private void jtfNewSubjectMidTermGradeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtfNewSubjectMidTermGradeMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfNewSubjectMidTermGradeMouseClicked

    private void jtfNewSubjectMidTermGradeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfNewSubjectMidTermGradeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfNewSubjectMidTermGradeActionPerformed

    private void jtfNewSubjectFinalTermScoreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtfNewSubjectFinalTermScoreMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfNewSubjectFinalTermScoreMouseClicked

    private void jtfNewSubjectFinalTermScoreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfNewSubjectFinalTermScoreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfNewSubjectFinalTermScoreActionPerformed

    private void jbSaveEditSubjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSaveEditSubjectActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbSaveEditSubjectActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JButton jbBack;
    private javax.swing.JButton jbSaveEditSubject;
    private javax.swing.JComboBox<String> jcbSubjects;
    private javax.swing.JPanel jpTeacherGradingManagementEditSubjectPanel;
    private javax.swing.JScrollPane jsResult;
    private javax.swing.JTable jtStudentResult;
    private javax.swing.JTextField jtfNewSubjectFinalTermScore;
    private javax.swing.JTextField jtfNewSubjectMidTermGrade;
    private javax.swing.JTextField jtfNewSubjectProgressGrade;
    // End of variables declaration//GEN-END:variables
}
