/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package studentgradingmanager.UI.student.jpanel;

/**
 *
 * @author Quan
 */
public class StudentAccountInfo extends javax.swing.JPanel {

    /**
     * Creates new form StudentAccountInfo
     */
    public StudentAccountInfo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpStudentAccountInfo = new javax.swing.JPanel();
        jlTest = new javax.swing.JLabel();

        jpStudentAccountInfo.setBackground(new java.awt.Color(255, 255, 255));
        jpStudentAccountInfo.setForeground(new java.awt.Color(255, 255, 255));

        jlTest.setText("account info");

        javax.swing.GroupLayout jpStudentAccountInfoLayout = new javax.swing.GroupLayout(jpStudentAccountInfo);
        jpStudentAccountInfo.setLayout(jpStudentAccountInfoLayout);
        jpStudentAccountInfoLayout.setHorizontalGroup(
            jpStudentAccountInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpStudentAccountInfoLayout.createSequentialGroup()
                .addGap(129, 129, 129)
                .addComponent(jlTest)
                .addContainerGap(205, Short.MAX_VALUE))
        );
        jpStudentAccountInfoLayout.setVerticalGroup(
            jpStudentAccountInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpStudentAccountInfoLayout.createSequentialGroup()
                .addGap(102, 102, 102)
                .addComponent(jlTest)
                .addContainerGap(182, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpStudentAccountInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpStudentAccountInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jlTest;
    private javax.swing.JPanel jpStudentAccountInfo;
    // End of variables declaration//GEN-END:variables
}
