/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package studentgradingmanager.UI.student.jpanel;

/**
 *
 * @author Quan
 */
public class StudentGradeResult extends javax.swing.JPanel {

    /**
     * Creates new form StudentGradeResutl
     */
    public StudentGradeResult() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpStudentGradeResult = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        jpStudentGradeResult.setBackground(new java.awt.Color(255, 255, 255));
        jpStudentGradeResult.setForeground(new java.awt.Color(255, 255, 255));

        jLabel1.setText("grade result");

        javax.swing.GroupLayout jpStudentGradeResultLayout = new javax.swing.GroupLayout(jpStudentGradeResult);
        jpStudentGradeResult.setLayout(jpStudentGradeResultLayout);
        jpStudentGradeResultLayout.setHorizontalGroup(
            jpStudentGradeResultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpStudentGradeResultLayout.createSequentialGroup()
                .addGap(155, 155, 155)
                .addComponent(jLabel1)
                .addContainerGap(182, Short.MAX_VALUE))
        );
        jpStudentGradeResultLayout.setVerticalGroup(
            jpStudentGradeResultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpStudentGradeResultLayout.createSequentialGroup()
                .addGap(107, 107, 107)
                .addComponent(jLabel1)
                .addContainerGap(177, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpStudentGradeResult, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpStudentGradeResult, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jpStudentGradeResult;
    // End of variables declaration//GEN-END:variables
}
